name: StackIt
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run dev

  frontend:
    build:
      context: ./userinterface
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "5173:4000"
    command: npm run dev